FROM alpine:3.14
CMD ["echo", "Eu sou Sarah uma mulher desemvolvedora na Trybe"]

# rodei no terminal da pasta do Dockerfile o comando: docker build -t primeira-imagem .
# passando um ponto no final do comando para indicar ao Docer que ;e para fazer a construção baseado na pasta atual
